# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

variables:
  imageName: robot_testenv
  imageTag: $(Build.BuildId)

stages:
- stage: Build
  displayName: Build Test Environment
  jobs:
  - job: Build
    displayName: Build jobs
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '19.03.5'
    - script: |
        docker build -t $(imageName):$(imageTag) .
        docker save $(imageName):$(imageTag) -o $(imageName)_$(imageTag).tar
      displayName: 'Build and Save Docker Image'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(imageName)_$(imageTag).tar'
        artifact: 'docker-image'
      displayName: 'Publish Docker Image'

- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test jobs
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'docker-image'
        path: '.'
      displayName: 'Download Docker Image'
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '19.03.5'   
    - script: |
        docker load -i $(imageName)_$(imageTag).tar
        chmod u+x ./run_suite.sh
        docker compose up
      displayName: Run Tests
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'reports/'
        artifact: 'reports'
      displayName: 'Publish Test Reports'
