services:
  chrome:
    image: testenv:latest
    volumes:
      - .:/robot
    environment:
      - BROWSER=chrome
      - BROWSER_VERSION=stable
      - OUTPUT_DIR=reports/chrome/
      - TAG=-i gui
      
  edge:
    image: testenv:latest
    volumes:
      - .:/robot
    environment:
      - BROWSER=edge
      - BROWSER_VERSION=stable
      - OUTPUT_DIR=reports/edge/
      - TAG=-i gui
      
  firefox:
    image: testenv:latest
    volumes:
      - .:/robot
    environment:
      - BROWSER=firefox
      - BROWSER_VERSION=stable
      - OUTPUT_DIR=reports/firefox/
      - TAG=-i gui

  api:
    image: testenv:latest
    volumes:
      - .:/robot
    environment:
      - OUTPUT_DIR=reports/api/
      - TAG=-i api  
