services:
  chrome:
    image: testenv:latest
    volumes:
      - .:/robot
    environment:
      - BROWSER=chrome
      - BROWSER_VERSION=beta
      - OUTPUT_DIR=reports/chrome/
      - TAG=-i gui
    restart: no

  edge:
    image: testenv:latest
    volumes:
      - .:/robot
    environment:
      - BROWSER=edge
      - BROWSER_VERSION=stable
      - OUTPUT_DIR=reports/edge/
      - TAG=-i gui
    restart: no

  firefox:
    image: testenv:latest
    volumes:
      - .:/robot
    environment:
      - BROWSER=firefox
      - BROWSER_VERSION=120
      - OUTPUT_DIR=reports/firefox/
      - TAG=-i gui
    restart: no

  api:
    image: testenv:latest
    volumes:
      - .:/robot
    environment:
      - OUTPUT_DIR=reports/api/
      - TAG=-i api
    restart: no    
